version:                "1"
services:
#  pkg:
#    image: pkg/pkg
#    build:
#      context: ./
#      dockerfile: ./docker/pkg/Dockerfile
##    volumes:
##      - ./notebooks:/home/jovyan/work
#    ports:
#      - 1167:8888
#    environment:
#      - JUPYTER_TOKEN=hi
  pop4sim_dev:
      image: jupyter/scipy-notebook:python-3.10.9
      volumes:
        - ./notebooks:/home/jovyan/work
        - ./src/pop4sim:/home/jovyan/work/pop4sim
      ports:
        - 8888:8888
      environment:
        - JUPYTER_TOKEN=hi
